version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/var/www
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    container_name: gaem_app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass1234
    ports:
      - "27017:27017"
    container_name: gaem_db