version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      MONGO_URI: mongo://root:pass1234@mongo:27017/gaem
    volumes:
      - .:/var/www
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    container_name: gaem_app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass1234
      MONGO_INITDB_DATABASE: gaem
    ports:
      - "27017:27017"
    container_name: gaem_db